### PR TITLE
add start and end time in glob request & maxDataPoints in fetch request

### PR DESCRIPTION
**Pull request by faceair**
When the storage engine is not a whisper, I need more information to find the metric.

When searching for a metric in grafana and selecting `On Time Range Change`, grafana will bring the requested time range with it.
image
image

Also backend needs to know maxDataPoints, which makes it easier to calculate the accuracy of the returned data, rather than fixing some accuracy value.

### CODE REVIEW

**Review by Civil — APPROVED** [review]

**Comment by faceair** [comment]
Hi @Civil 
Can you release a new version? I'm going to upgrade protocol on carbonapi.

**Comment by Civil** [comment]
Done

**Comment by faceair** [comment]
0.4.3 is not a valid version number, can be changed to v0.4.3.

**Comment by Civil** [comment]
You are right. Fixed now.

**Pull request merged**
